"""Initial Migration

Revision ID: 21febe88833a
Revises: 
Create Date: 2022-11-10 16:37:39.154754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21febe88833a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
