"""added profile pic field

Revision ID: 812735ca7c05
Revises: fef0594d0724
Create Date: 2022-11-18 23:55:46.178938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812735ca7c05'
down_revision = 'fef0594d0724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
